### ISSUE TITLE
playerCurrentJourney() only handles case where there's only one journey for player

### ISSUE THREAD

**Issue by rocketbootkid** [rocketbootkid/Random-Hackcess#10]
This isn't a big deal, but the identification of "current journey" when journey switching in the journeys list doesn't work for anyone apart from character 1.

**Comment by rocketbootkid** [comment]
Instead, move the list of journeys inside the character table, so that for each character there is a list of their journeys.

**Comment by rocketbootkid** [comment]
In fact, change the initial pages to, in order;
1. Player Select
2. Character Select
3. Journey Select

**Comment by rocketbootkid** [comment]
All done, except you can't select a journey if there's only one.

**Comment by dittoslash** [comment]
If there's one journey you don't need to switch between multiple.

**Comment by rocketbootkid** [comment]
Done.
