### ISSUE TITLE
Generate Features on generation of a new grid

### ISSUE THREAD

**Issue by rocketbootkid** [rocketbootkid/Random-Hackcess#2]
- Feature Types
  - Fight (fight enemy, gain XP / items / gold)
  - Store (buy / sell stuff)
  - Helpful Stranger (gives you stuff)
  - Teleport (teleports you to a random new grid)
- Single Feature per grid
- Presence of a feature at a grid will be represented using a blue-coloured surround to the grid (red is current position, green is the start point).

**Comment by dittoslash** [comment]
New feature type:
 Log (points out coordinates that will be generated as a certain feature type)

**Comment by rocketbootkid** [comment]
I don't get what you mean. Features exist at a grid location, for which coordinates are always generated. Features will be randomly generated when the grid location is generated. You won't know in advance where a feature will be generated.

The frequency of feature generation will vary;
- Fight: Common (1:5) - Grid border style: red solid
- Store: Uncommon (1:20) - Grid border style: green solid
- Helpful Stranger (1:30) - Grid border style: green dashed
- Teleport (1:30) - Grid border style: blue dashed

When you speak to a helpful stranger, they might tell you of a certain feature at a location (which will cause that grid / feature to be generated but won't move you there).

**Comment by dittoslash** [comment]
Oh, okay

**Comment by dittoslash** [comment]
My idea would do just what you said at the end there

**Comment by rocketbootkid** [comment]
Basic structure in place. Only worked on teleport feature.
However, teleport implementation needs work. It will currently work, but if the new grid is next to an existing grid, there's no guarantee that it will join up. It needs to use the same logic as used when moving to a new square.

**Comment by rocketbootkid** [comment]
If a grid is a dead end, it's automatically a fight with something.

**Comment by rocketbootkid** [comment]
Addressed the "dead end results in a fight" bit.

Still need to alter the teleport function to use the same logic as moving to a new grid.

**Comment by rocketbootkid** [comment]
Splitting into separate issues.
