### ISSUE TITLE
Combat

### ISSUE THREAD

**Issue by rocketbootkid** [rocketbootkid/Random-Hackcess#3]
One of the possible features on a grid is combat.

**Comment by dittoslash** [comment]
Duplicate

**Comment by rocketbootkid** [comment]
Need to keep this open to detail how combat will work

**Comment by rocketbootkid** [comment]
- Combat will be managed on a separate page
- Enemies will be auto-generated, their statistics based on that of the character (so that enemies are beatable, not OP)
- Character can decide to fight or run
  - If character runs, they lose some HP and perhaps some XP
  - If character fights, the fight will be automatically run, with the combat page rolling dice using the character and enemy stats to determine the victor.
- Character will be given XP if they win.
  - The speed of the victory will result in more XP
- Enemies may drop items or gold
  - The Character will automatically pickup the gold, but must choose whether to pick up the item.

**Comment by rocketbootkid** [comment]
If a player moves onto a grid and it is determined that an enemy is there, the player is automatically redirected to the battle page.

**Comment by rocketbootkid** [comment]
Battle page created, including comparison table displaying character vs enemy stats.

**Comment by rocketbootkid** [comment]
Fight mechanics working and tweaked. Next step is to manage aftermath.

**Comment by rocketbootkid** [comment]
Done.
