### ISSUE TITLE
Feature: Store

### ISSUE THREAD

**Issue by rocketbootkid** [rocketbootkid/Random-Hackcess#4]
- One of the possible features for a grid is a Store. 
- A character will be able to buy / sell items using their gold.

**Comment by dittoslash** [comment]
Duplicate

**Comment by rocketbootkid** [comment]
Need to keep this open to discuss Store features

**Comment by rocketbootkid** [comment]
- Store will be a separate page
- Items will be basic in nature (at least initially). Nothing magic, just basic AC boost (armour, shields) or ATK boost (weapons)
- Items and Item details will be randomly generated.
- Items will have four modifying attributes
  - AC - bonus to Defence
  - ATK - bonus to Attack
  - Weight - used to limit amount of equipment someone can carry.
  - Value - cost in gold
- Items may be sold for their entire value.

**Comment by rocketbootkid** [comment]
- Separate store page
- Store is generated on the first visit to the grid
- Store is saved and may be revisited.
- Store contents will have 0-2 of each item (head, chest, legs, shield, weapon)
- Store will have a proprietor
- New table to store contents of the store.
- On right side of the page will be contents of the character's bag.
- Includes stuff the player is wearing (indicate this in the store)
- Player can buy / sell between the store and their bag.
