### ISSUE TITLE
Feature: Heat Map

### ISSUE THREAD

**Issue by rocketbootkid** [rocketbootkid/Random-Hackcess#47]
A data visualization of how often each of the squares in the grid have been visited across all the journeys.

**Comment by dittoslash** [comment]
Would be good to test randomness level.

**Comment by dittoslash** [comment]
50c849652066c6c5ee04c1f9888c913cfab36d67: allTilesArray()

**Comment by rocketbootkid** [comment]
Mostly done, but the color gradient is kicking my ass.
