### ISSUE TITLE
Rogue-like character creation

### ISSUE THREAD

**Issue by rocketbootkid** [rocketbootkid/Random-Hackcess#6]
- Once combat is sorted, introduce rogue-like character creation.
- When a character dies (or player chooses to retire them), a child character is created.
- Elements of the character are inherited from the parent character
  - 2 of their items (randomly selected)
  - 10% of their gold
  - 50% of the HP gain (minus armour bonus)
  - 50% of the ATK gain (minus weapon bonus)
  - 25% of the STR gain

**Comment by dittoslash** [comment]
Roguedom-Hacklegacy
