### ISSUE TITLE
Create initial Journal entry when a new journey is created.

### ISSUE THREAD

**Issue by rocketbootkid** [rocketbootkid/Random-Hackcess#9]
Add INSERT to hackcess.journal in newJourney();

"Dropped off at x,y in [Journey Name]".

**Comment by dittoslash** [comment]
fits nicely with the lore :+1:

**Comment by rocketbootkid** [comment]
Yes, I based it off your airship idea.

**Comment by dittoslash** [comment]
anywhere i can test this? (my local apache is still pooped)

**Comment by dittoslash** [comment]
also, https://waffle.io/rocketbootkid/Random-Hackcess

**Comment by rocketbootkid** [comment]
Fixed
